### PR TITLE
Use SocketError for DNS errors

### PR DESCRIPTION
**Pull request by fw42**
Fixes https://github.com/redis/hiredis-rb/issues/40.

Doesn't seem like the cleanest solution... Any suggestions?

@badboy @byroot

### CODE REVIEW

**Comment by byroot** [comment]
> Doesn't seem like the cleanest solution.

LGTM, what is bothering you?

**Comment by fw42** [comment]
Hm I guess what's bothering me is the fact that `else if (err == REDIS_ERR_OTHER) { ... }` could maybe also catch other, non DNS-related, errors..

**Comment by byroot** [comment]
Oh I see, I missed that.

Well, SocketError would be nice so that the behavior is the same than without `hiredis`, but in the end I think the root cause is that raising `RuntimeError` doesn't seem sensible.

Couldn't we raise a `Redis::BaseError` or something like this?

**Comment by fw42** [comment]
Closing since there's nothing happening here

**Comment by erated** [comment]
Any updates on this? Runtime error sucks and prevents from creating real error handling. 
"RuntimeError: Name or service not known". These are cluttering our logs and making me think that we should potentially switch back to the default redis client as we cant handle these gracefully.

**Pull request closed without merging**
